application: appbooleantest
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py
  
- url: /thanks/
  script: thanks.py
  
- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
  
